### ISSUE TITLE
removeItemBuilder does not provide an index but itemBuilder does when removing

### ISSUE THREAD

**Issue by Jan-pp** [bnxm/implicitly_animated_reorderable_list#29]
When you do not provide a `removeItemBuilder` it defaults to `itemBuilder` for removing. The `itemBuilder` does provide an index also when it is called to remove an item. However when you use `removeItemBuilder` it does not provide you with this index.

So can you add the index to the `removeItemBuilder` just like the `itemBuilder`?

**Comment by bnxm** [comment]
When an item was removed, the index wouldn't correspond to the correct item in the list anymore or may even throw when trying to access an item using that index and thus isn't supplied to prevent people from making unsafe operations. I'm not sure if I should change that because usually, if possible, you should not rely on the index at all, however I'll think about adding it.

**Comment by Jan-pp** [comment]
Thanks I understand what you mean. I actually just use the index to check if it is odd or even so I can alternate between white and gray background.

Maybe another option would be to add an extra argument to `ItemBuilder` named `delete` which is true if it is called because of deletion. It would make the `removeItemBuilder` redundant (but keep it for compatibility of course).

Or for consistency if the `itemBuilder` is called when deleting have its index argument set to `null`. However this way I can't check anymore if the deleted item is odd or even.

**Comment by yasinarik** [comment]
@bnxm  I am building the items of the listview not only dependent on the `item` data but also the `index`. 

So, since the `removeItemBuilder` doesn't provide an index, I can't build the items. Any chances that you also let us have the removed index? For the data part of it, of course, I will use the actual data parameter `item`. However, I still need an index.

If my approach is wrong please tell me why. Thank you so much for building this package, is a lifesaver.
