### ISSUE TITLE
ImplicitlyAnimatedList ignores physics?

### ISSUE THREAD

**Issue by agordeev** [bnxm/implicitly_animated_reorderable_list#41]
I use it this way:

```dart
ImplicitlyAnimatedList<JournalListItem>(
      physics: const BouncingScrollPhysics(),
      ....
```

with only one item populated.

However, the list doesn't bounce. `ClampingScrollPhysics` doesn't clamp.

**Comment by bnxm** [comment]
> I use it this way ... with only one item populated.

As far as I can tell this is the expected behavior and the case for every `Scrollable` in flutter. `ScrollPhysics` seems to only take effect when the `Scrollable` is actually scrollable:

~~~dart
ListView(
  physics: const BouncingScrollPhysics(),
  children: [
    Container(
      height: 300,
      color: Colors.red,
    ),
    Container(
      height: 300,
      color: Colors.green,
    ),
  ],
)
~~~

This `ListView` also doesn't bounce unless I add a third `Container`, so that the viewport is larger than the screen size (you might have to adjust the height for your screen size).
