### ISSUE TITLE
Handle gets triggered when nested reorderable list is scrolled 

### ISSUE THREAD

**Issue by jeffsieu** [bnxm/implicitly_animated_reorderable_list#8]
This problem is similar to the one in #3.

However for me, since my `ImplicitlyAnimatedReorderableList` is inside of a `CustomScrollView`, I have its scroll physics set to `NeverScrollableScrollPhysics`. Whenever I scroll the `CustomScrollView`, it doesn't register this as a scroll inside `Handle` because the `ImplicitlyAnimatedReorderableList` isn't the one scrolling, so its `ScrollController` doesn't actually think anything is scrolling.

My code structure is something like this:
```
CustomScrollView(
    controller: _scrollController,
    slivers: <Widget>[
        ...,
        SliverToBoxAdapter(
            child: ImplicitlyAnimatedReorderableList(
                physics: const NeverScrollableScrollPhysics(),
                shrinkWrap: true,
                ...,
            )
        ),
        ...,
    ]
)
```

For now I'm fixing it by modifying the `_HandleState` class with the following.

```
class _HandleState extends State<Handle> {
	...
	
	double _deltaThreshold = 4.0;
	double _currentDelta = 0.0;
	
	...
	
	// Reset delta after cancelling the reorder
	void _cancelReorder() {
		...
		_currentDelta = 0.0;
		...
	  }
	
	...

	@override
	Widget build(BuildContext context) {
		...

		return Listener(
			...
			onPointerMove: (PointerMoveEvent event) {
				final Offset pointer = event.localPosition;
				final double delta = _isVertical ? event.delta.dy : event.delta.dx;
				
				// If pointer moves more than threshold amount, cancel reorder
				_currentDelta += delta;
				if (!_inDrag && _currentDelta.abs() > _deltaThreshold) {
				  _cancelReorder();
				}
				...
			}
		);
	}
}
```

**Comment by BendixMa** [comment]
Hey, thanks for the issue!

Nested scrolling is indeed not yet supported but as part of #7 I will work on implementing support for `NestedListViews/CustomScrollViews` in an upcoming version.

Alas, I'm quite busy currently so you might need a bit of patience with me because it might take a few days/weeks before I can create a stable version that fixes those issues, that I can then publish on pub.

**Comment by bnxm** [comment]
Version `0.2.0` should fix this now when the `ImplicitlyAnimatedReorderableList` is nested inside another `Scrollable` and `physics` is set to `NeverScrollableScrollPhysics`.

**Comment by peterstojanowski** [comment]
Hi @bnxm, is there anything else apart from `physics` that needs to be set on the `ImplicitlyAnimatedReorderableList` ? I have a `ListView` that contains a `ImplicitlyAnimatedReorderableList` and when I reorder items the whole `ListView` still scrolls. I'm using version 0.2.1.

**Comment by bnxm** [comment]
Yes. If the list is nested inside another scrollable than you would have to set `NeverscrollableScrollPhysics` on the parent list while the item is being reordered. You can use a boolean flag for this and the `onReorderStarted` and `onReorderFinished` callbacks. The example app exemplifies this. This is sadly the only way how this is possible, because `Scrollable` doesn't expose a public method I know of that could disable scrolling. If you want to display a widget before or after the list you can also use the `header` or `footer` parameter. 

This issue was about not invoking a reorder/drag when the parent list scrolled.
